#!/bin/bash

# Generate a Windows bundle for running Geth v1.1.0 with static peering to the deployed VM geth v1.3.6.
#
# Output:
#   chain-of-geths/generated-files/geth-windows-v1.1.0.zip
#
# The ZIP contains:
#   - the official Geth v1.1.0 Win64 release contents (downloaded from GitHub)
#   - a `data/` directory with `static-nodes.json` configured to *only* peer to the VM
#   - a helper `run-geth-v1.1.0.bat` that starts geth with discovery disabled

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Load local env overrides (VM_IP, etc.).
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
if [ ! -f "$ENV_FILE" ] && [ -f "$ENV_EXAMPLE" ]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  echo "Created $ENV_FILE from $ENV_EXAMPLE (edit as needed)" >&2
fi
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck source=/dev/null
  . "$ENV_FILE"
  set +a
fi

OUTPUT_DIR="$SCRIPT_DIR/generated-files"
mkdir -p "$OUTPUT_DIR"

OUT_ZIP="$OUTPUT_DIR/geth-windows-v1.1.0.zip"

# Official release ZIP.
# Source: https://github.com/ethereum/go-ethereum/releases/tag/v1.1.0
GETH_WIN_ZIP_URL="${GETH_WIN_ZIP_URL:-https://github.com/ethereum/go-ethereum/releases/download/v1.1.0/Geth-Win64-20150825140940-1.1.0-fd512fa.zip}"

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd" >&2
    exit 1
  fi
}

require_cmd curl
require_cmd unzip
require_cmd zip
require_cmd docker

# Determine the VM's public IP for a Windows->VM enode.
get_vm_ip() {
  # Priority:
  #   1) explicit environment variable
  #   2) read from local .env / .env.example (sourced above)
  if [[ -n "${VM_IP:-}" ]]; then
    echo "${VM_IP}"
    return 0
  fi
  echo ""
}

VM_IP_FOR_WINDOWS="$(get_vm_ip)"
if [[ -z "$VM_IP_FOR_WINDOWS" ]]; then
  cat >&2 <<'EOF'
Could not determine VM public IP for the Windows bundle.

Fix:
  VM_IP=<your-vm-public-ip> ./generate-windows-zip.sh
EOF
  exit 1
fi

# Extract the v1.3.6 P2P port from docker-compose.yml (so we don't drift if the compose file changes).
get_v1_3_6_p2p_port() {
  local compose="$SCRIPT_DIR/docker-compose.yml"
  if [[ ! -f "$compose" ]]; then
    echo "30311"
    return 0
  fi

  # Find the first `--port <N>` inside the `geth-v1-3-6` service block.
  local port
  port=$(awk '
    /^  geth-v1-3-6:/ {in_block=1; next}
    in_block && /^  [A-Za-z0-9_.-]+:/ {in_block=0}
    in_block && /--port[[:space:]]+[0-9]+/ {
      for (i=1; i<=NF; i++) if ($i=="--port") { print $(i+1); exit }
    }
  ' "$compose")

  if [[ -n "$port" && "$port" =~ ^[0-9]+$ ]]; then
    echo "$port"
  else
    # Fallback to the historical default used by this stack.
    echo "30311"
  fi
}

V1_3_6_P2P_PORT_DEFAULT="$(get_v1_3_6_p2p_port)"
# Allow explicit override, but default to whatever docker-compose.yml currently says.
V1_3_6_P2P_PORT="${V1_3_6_P2P_PORT:-$V1_3_6_P2P_PORT_DEFAULT}"

# Derive the v1.3.6 pubkey from its nodekey (generated by generate-keys.sh).
NODEKEY_PATH="$OUTPUT_DIR/data/v1.3.6/nodekey"
if [[ ! -f "$NODEKEY_PATH" ]]; then
  cat >&2 <<'EOF'
Missing generated-files/data/v1.3.6/nodekey.

Fix:
  ./generate-keys.sh

Then re-run:
  ./generate-windows-zip.sh
EOF
  exit 1
fi

echo "Deriving VM-reachable enode for geth v1.3.6..."
raw=$(docker run --rm -v "$NODEKEY_PATH:/nodekey:ro" ethereum/client-go:v1.16.7 \
  --datadir /tmp \
  --nodekey /nodekey \
  --port "$V1_3_6_P2P_PORT" \
  --nodiscover \
  --ipcdisable \
  --http \
  --http.api admin \
  console --exec "admin.nodeInfo.enode" 2>&1 | tr -d '\r' | grep -Eo 'enode://[0-9a-fA-F]+@[^ ]+' | head -n 1)
pubkey=$(echo "$raw" | sed -E 's#^enode://([^@]+)@.*#\1#')
if [[ -z "$pubkey" || "$pubkey" == "enode://" ]]; then
  echo "Failed to extract pubkey from enode output. Raw: '$raw'" >&2
  exit 1
fi

# Windows geth v1.1.0 is extremely old; avoid enode query strings.
WINDOWS_ENODE="enode://$pubkey@$VM_IP_FOR_WINDOWS:$V1_3_6_P2P_PORT"

tmp="$(mktemp -d)"
cleanup() { rm -rf "$tmp"; }
trap cleanup EXIT

dl_zip="$tmp/geth-v1.1.0-win64.zip"
extract_dir="$tmp/extract"
pkg_dir="$tmp/pkg"
mkdir -p "$extract_dir" "$pkg_dir"

echo "Downloading Geth v1.1.0 Win64 release..."
curl -L --fail -o "$dl_zip" "$GETH_WIN_ZIP_URL"

echo "Extracting release zip..."
unzip -q "$dl_zip" -d "$extract_dir"

# The release zip sometimes contains a single top-level directory and sometimes extracts files
# directly into the output dir. Handle both.
top="$(find "$extract_dir" -mindepth 1 -maxdepth 1 -type d | head -n 1 || true)"
if [[ -n "$top" ]]; then
  cp -a "$top"/* "$pkg_dir"/
else
  cp -a "$extract_dir"/* "$pkg_dir"/
fi

mkdir -p "$pkg_dir/data"
printf '["%s"]\n' "$WINDOWS_ENODE" > "$pkg_dir/data/static-nodes.json"

cat > "$pkg_dir/run-geth-v1.1.0.bat" <<'BAT'
@echo off
setlocal

REM Run Geth v1.1.0 with discovery disabled and only a single static peer.
REM The peer is configured in: data\static-nodes.json

REM If 30303 is in use, change --port.
geth.exe --datadir data --networkid 1 --port 30303 --nodiscover --bootnodes "" --maxpeers 1

endlocal
BAT

cat > "$pkg_dir/README.txt" <<TXT
Windows Geth v1.1.0 static peering bundle

Contents:
  - Official Geth v1.1.0 Win64 binaries
  - data\static-nodes.json: a single static peer to the hosted VM geth v1.3.6
  - run-geth-v1.1.0.bat: starts geth with discovery disabled

How to use:
  1) Extract this zip.
  2) Run: run-geth-v1.1.0.bat

Static peer:
  - VM host: $VM_IP_FOR_WINDOWS
  - VM P2P port: $V1_3_6_P2P_PORT
  - Enode: $WINDOWS_ENODE

Notes:
  - This only configures peering. You still need appropriate chain data for an ancient client.
  - The hosted VM must allow inbound TCP/UDP on the v1.3.6 P2P port.
TXT

echo "Creating $OUT_ZIP ..."
rm -f "$OUT_ZIP"
(cd "$pkg_dir" && zip -qr "$OUT_ZIP" .)

echo "Wrote: $OUT_ZIP"
